-- MySQL Script generated by MySQL Workbench
-- Thu Aug 22 00:14:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fishing
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fishing` ;

-- -----------------------------------------------------
-- Schema fishing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fishing` DEFAULT CHARACTER SET utf8 ;
USE `fishing` ;

-- -----------------------------------------------------
-- Table `fishing`.`moon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fishing`.`moon` ;

CREATE TABLE IF NOT EXISTS `fishing`.`moon` (
  `date` DATE NOT NULL,
  `region` VARCHAR(32) NOT NULL,
  `expect_date` DATETIME NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`date`, `expect_date`, `region`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fishing`.`sun`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fishing`.`sun` ;

CREATE TABLE IF NOT EXISTS `fishing`.`sun` (
  `date` DATE NOT NULL,
  `region` VARCHAR(32) NOT NULL,
  `expect_date` DATETIME NOT NULL,
  `first_light` VARCHAR(16) NOT NULL,
  `sunrise` VARCHAR(16) NOT NULL,
  `sunset` VARCHAR(16) NOT NULL,
  `last_light` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`date`, `expect_date`, `region`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fishing`.`tide`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fishing`.`tide` ;

CREATE TABLE IF NOT EXISTS `fishing`.`tide` (
  `date` DATE NOT NULL,
  `region` VARCHAR(32) NOT NULL,
  `expect_date` DATETIME NOT NULL,
  `time` DATETIME NOT NULL,
  `height` FLOAT NOT NULL,
  PRIMARY KEY (`date`, `region`, `expect_date`, `time`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fishing`.`rainfall`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fishing`.`rainfall` ;

CREATE TABLE IF NOT EXISTS `fishing`.`rainfall` (
  `date` DATE NOT NULL,
  `region` VARCHAR(32) NOT NULL,
  `expect_date` DATETIME NOT NULL,
  `possibility` VARCHAR(32) NULL,
  `amount` VARCHAR(32) NULL,
  PRIMARY KEY (`date`, `region`, `expect_date`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fishing`.`rainfall_possibility`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fishing`.`rainfall_possibility` ;

CREATE TABLE IF NOT EXISTS `fishing`.`rainfall_possibility` (
  `date` DATE NOT NULL,
  `region` VARCHAR(32) NOT NULL,
  `expected_timestamp` INT NOT NULL,
  `possibility` FLOAT NOT NULL,
  PRIMARY KEY (`date`, `region`, `expected_timestamp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fishing`.`swell`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fishing`.`swell` ;

CREATE TABLE IF NOT EXISTS `fishing`.`swell` (
  `date` DATE NOT NULL,
  `region` VARCHAR(32) NOT NULL,
  `expected_timestamp` INT NOT NULL,
  `height` FLOAT NOT NULL,
  `direction` VARCHAR(8) NOT NULL,
  `period` FLOAT NOT NULL,
  PRIMARY KEY (`date`, `region`, `expected_timestamp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fishing`.`wind`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fishing`.`wind` ;

CREATE TABLE IF NOT EXISTS `fishing`.`wind` (
  `date` DATE NOT NULL,
  `region` VARCHAR(32) NOT NULL,
  `expected_timestamp` INT NOT NULL,
  `speed` FLOAT NOT NULL,
  `direction` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`date`, `region`, `expected_timestamp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fishing`.`temperature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fishing`.`temperature` ;

CREATE TABLE IF NOT EXISTS `fishing`.`temperature` (
  `date` DATE NOT NULL,
  `region` VARCHAR(32) NOT NULL,
  `expected_timestamp` INT NOT NULL,
  `temperature` FLOAT NOT NULL,
  PRIMARY KEY (`date`, `region`, `expected_timestamp`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
